### PR TITLE
Fixed an NPE in the `EvaluationOrderGraph` if the `iterationStatement` of a `ForStatement` was null.

### LINKED ISSUE #1015: node.iterationStatement is null to the format "for( ; ; )"
When the following `ForStatement` appears, the `NullPointerException` occurs
```java
public void test(){
    for (;;){
        System.out.println("1");
    }
}
```
exception
```java
java.util.concurrent.ExecutionException: java.lang.NullPointerException: node.iterationStatement must not be null
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1999)
	at com.huawei.cra.core.core.CodePropertyGraph.buildCPG(CodePropertyGraph.java:69)
	... 28 more
Caused by: java.lang.NullPointerException: node.iterationStatement must not be null
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.handleForStatement(EvaluationOrderGraphPass.kt:883)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass._init_$lambda$20(EvaluationOrderGraphPass.kt:135)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.createEOG(EvaluationOrderGraphPass.kt:403)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.handleCompoundStatement(EvaluationOrderGraphPass.kt:510)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass._init_$lambda$14(EvaluationOrderGraphPass.kt:122)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.createEOG(EvaluationOrderGraphPass.kt:403)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.handleFunctionDeclaration(EvaluationOrderGraphPass.kt:347)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass._init_$lambda$4(EvaluationOrderGraphPass.kt:92)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.createEOG(EvaluationOrderGraphPass.kt:403)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.handleRecordDeclaration(EvaluationOrderGraphPass.kt:299)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass._init_$lambda$3(EvaluationOrderGraphPass.kt:89)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.createEOG(EvaluationOrderGraphPass.kt:403)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.handleTranslationUnitDeclaration(EvaluationOrderGraphPass.kt:270)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass._init_$lambda$1(EvaluationOrderGraphPass.kt:83)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.createEOG(EvaluationOrderGraphPass.kt:403)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.accept(EvaluationOrderGraphPass.kt:209)
	at de.fraunhofer.aisec.cpg.passes.EvaluationOrderGraphPass.accept(EvaluationOrderGraphPass.kt:69)
	at de.fraunhofer.aisec.cpg.TranslationManager.analyze$lambda$2(TranslationManager.kt:102)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```
configuration: version 5.1.0
```java
     TranslationConfiguration.Builder()
                .sourceLocations(new File(fileName))
                .topLevel(null)
                .defaultPasses()
                .registerLanguage(JavaLanguageFrontend.class, JavaLanguageFrontend.JAVA_EXTENSIONS)
                .loadIncludes(false)
                .debugParser(false)
                .build();
```

### PR DESCRIPTION
**Pull request by oxisto**
This was the result of a mixed Kotlin/Java conversion. I have now also converted the `ForStatement` to Kotlin, so all static null checks should not work properly.

Fixes #1015

### CODE REVIEW

File: cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/enhancements/EOGTest.kt [hunk 1]
```diff
@@ -321,21 +321,21 @@ internal class EOGTest : BaseTest() {
...
                 cr = Connect.SUBTREE,
-                refs = listOf(fs.condition)
+                refs = listOf(fs.condition!!)
             )
         )
         assertTrue(
             Util.eogConnect(
                 en = Util.Edge.EXITS,
-                n = fs.condition,
+                n = fs.condition!!,
```
Comment (konradweiss) [inline cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/enhancements/EOGTest.kt:338]: is the compiler asking for them now? They were not necessary when I added the changes to the function

**Review by konradweiss — APPROVED** [review]
There is still a compilation error in the `MultiValueEvaluator.kt: (253, 55): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type Statement?`

File: cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/enhancements/EOGTest.kt (hunk 1 above)
Comment (oxisto) [reply cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/enhancements/EOGTest.kt:338]: The problem was that `condition` was always nullable, however this was never explicitly modelled as such in the Java class. Now after converting to Kotlin it is definitely a nullable `Node?` and now Kotlin complains, since eogConnect wants a `Node`. I was playing around with making arguments of the function to accept `Node?` but I somehow lost my nerve :D

Comment (oxisto) [reply cpg-core/src/test/kotlin/de/fraunhofer/aisec/cpg/enhancements/EOGTest.kt]: I may have a solution that now does not have any `!!`

**Review by KuechA — APPROVED** [review]
