### PR TITLE
Correct parsing of functions in namespaces in C++

### LINKED ISSUE #1070: fullName property is incomplete when using namespaces
# Unexpected behavior

The namespace is missing in the `fullName` property of the type node.
For c++, the default namespace within a function definition is the namespace of function itself.
The cpg does not take this into account and creates a new type, outside the namespace.

image

# Code of interest

```c++
namespace ABC {
        struct A {
        };
        void foo();
        void bar(ABC::A a);
};

void ABC::foo() {
        A a;
        bar(a);
}

void ABC::bar(ABC::A a) {
}

```

# Extensions to the library, e.g. added or changed LanguageFrontends or Passes

None

# Changes to the configuration

None

### PR DESCRIPTION
**Pull request by oxisto**
Furthermore, this tries to mitigate the problem that types used within such a function could refer to a namespaced entity but are referred with its local name. Since this requires resolving of symbols in a frontend, we introduce a new annotaiton `@ResolveInFrontend` to warn developers.

Fixes #1070

### CODE REVIEW

File: cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationHandler.kt [hunk 1]
```diff
@@ -213,11 +215,12 @@ class DeclarationHandler(lang: CXXLanguageFrontend) :
 
         frontend.processAttributes(declaration, ctx)
 
-        frontend.scopeManager.leaveScope(declaration)
-        if (recordDeclaration != null && outsideOfRecord) {
-            frontend.scopeManager.leaveScope(recordDeclaration)
+        if (holder != null && outsideOfScope) {
```
Comment (konradweiss) [inline cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationHandler.kt:218]: Why are we leaving the scope of the holder before the scope of the declaration? We enter them in order ``holder -> declaration` so we should leave them in the order `declaration -> holder` right? Maybe I am missing something. In this case it would not make a difference though, I think.

**Review by konradweiss — CHANGES_REQUESTED** [review]

File: cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationHandler.kt (hunk 1 above)
Comment (oxisto) [reply cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationHandler.kt:218]: You are correct. This was probably a problem by moving code fragments around.

Comment (oxisto) [reply cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationHandler.kt:220]: Reverted back to the previous correct way.

**Comment by oxisto** [comment]
@konradweiss Once this is merged, a 6.1 release would be nice

**Review by konradweiss — APPROVED** [review]
