### PR TITLE
Handle `InitializerListExpression`s as variables of `ComprehensionExpression`s in the DFG

### LINKED ISSUE #1957: `InitializerListExpression` is not yet supported in the `ComprehensionExpression` in the CF-DFG pass
When analysing real-world python code, such as OpenStack, I get A LOT of these exceptions.

```
21:21:59,335 ERROR ControlFlowSensitiveDFGPass The variable of type class de.fraunhofer.aisec.cpg.graph.statements.expressions.InitializerListExpression is not yet supported in the ComprehensionExpression
```

### PR DESCRIPTION
**Pull request by KuechA**
Adapts the `ControlFlowSensitiveDFGPass` to handle multiple declarations and references in the variable of `ComprehensionExpression`s. To enhance the readability, the logic is moved to an own function.

Fixes #1957, #2017 

It further introduces a new interface `HasAccess` for Nodes which can be read from or written to. This allows to set the attribute `access: AccessValues` for more nodes than `Reference` and it also allows to implement a propagation logic per node class. Currently, the classes `Reference`, `InitializerListExpression` and `SubscriptExpression` implement this interface. It is mainly used to determine the direction of DFG edges.

### CODE REVIEW

File: cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Interfaces.kt [hunk 1]
```diff
@@ -149,3 +149,11 @@ interface HasOverloadedOperation : HasOperatorCode {
      */
     val operatorBase: Expression
 }
+
+interface HasAccess {
```
Comment (oxisto) [inline cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Interfaces.kt:153]: add a small doc string for the interface itself please.

File: cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/ForEachStatement.kt [hunk 2]
```diff
@@ -47,7 +46,7 @@ class ForEachStatement : LoopStatement(), BranchingNode, StatementHolder {
         astOptionalEdgeOf<Statement>(
             onChanged = { _, new ->
                 val end = new?.end
-                if (end is Reference) {
+                if (end is HasAccess) {
```
Comment (oxisto) [inline cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/ForEachStatement.kt:49]: Could be written as `(end as? HasAccess)?.access = ....` to be consistent with the other assignments.

File: cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/AssignExpression.kt [hunk 3]
```diff
@@ -72,9 +72,9 @@ class AssignExpression :
                 }
 
                 if (isSimpleAssignment) {
```
Comment (oxisto) [inline cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/AssignExpression.kt:74]: Could be written as 
```kotlin
(end as? HasAccess)?.access = if(isSimpleAssignment) {
  AccessValues.WRITE
} else {
  AccessValues.READWRITE
}
```

File: cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/ComprehensionExpression.kt [hunk 4]
```diff
@@ -43,7 +44,7 @@ class ComprehensionExpression : Expression(), ArgumentHolder {
             of = ProblemExpression("Missing variableEdge in ${this::class}"),
             onChanged = { _, new ->
                 val end = new?.end
-                if (end is Reference) {
+                if (end is HasAccess) {
```
Comment (oxisto) [inline cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/expressions/ComprehensionExpression.kt:47]: (it.end as? HasAccess)?.access to be consistent

File: cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Interfaces.kt [hunk 5]
```diff
@@ -149,3 +149,11 @@ interface HasOverloadedOperation : HasOperatorCode {
...
+    /**
+     * Is this reference used for writing data instead of just reading it? Determines dataflow
+     * direction
+     */
+    var access: AccessValues
```
Comment (oxisto) [inline cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Interfaces.kt:158]: On second thought. Wouldn't it make sense to just implements this on all `Expression` nodes? The memory overhead is probably negligible and we would remove a lot of ugly `as? HasAccess`  casts. Basically this should apply to all expressions.

File: cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.kt [hunk 6]
```diff
@@ -538,6 +505,53 @@ open class ControlFlowSensitiveDFGPass(ctx: TranslationContext) : EOGStarterPass
...
+                    is SubscriptExpression -> (writtenToIt.arrayExpression as? Reference)?.refersTo
+                    else -> {
+                        log.error(
+                            "The variable of type ${writtenToIt.javaClass} is not yet supported in the ComprehensionExpression"
+                        )
+                        null
+                    }
+                }
+
+            // state.push(writtenToIt, PowersetLattice(identitySetOf(currentNode.iterable)))
```
Comment (oxisto) [inline cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.kt:546]: leftover?

**Review by oxisto — COMMENTED** [review]
Some smaller remarks. In general this looks good, but I wonder whether we should move `access` to `Expression`.

File: cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Interfaces.kt (hunk 5 above)
Comment (KuechA) [reply cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Interfaces.kt:158]: I decided against this because many `Expression`s cannot receive any data (i.e., `AccessValues.WRITE` never makes sense for them and for some, also `READ` might be confusing), so the access value is not useful there. Are the casts are a major concern? Any opinions on this @konradweiss ?

Comment (oxisto) [reply cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Interfaces.kt:161]: But all of them (most?) are part of the DFG and it is interesting to have a harmonized way to access this information even for a lot of them it will statically stay with READ.

Comment (oxisto) [reply cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Interfaces.kt:161]: Probably altough a little bit awkward :(

Comment (KuechA) [reply cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Interfaces.kt]: Well, I kept it with Expressions for now and removed the interface.

Comment (oxisto) [reply cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/Interfaces.kt]: Sounds like a reasonable compromise

**Review by oxisto — APPROVED** [review]
A little but "controversial" to fix the access here in this PR but its ok in my opinion. Let's move forward with this.
