### PR TITLE
Copy objects less frequently

### LINKED ISSUE #1194: StackOverflowError in subtype listening system
Hey everyone, 

when trying to launch the cpg-neo4j, I get a `java.lang.StackOverflowError`. 
See the full log output [here](https://github.com/Fraunhofer-AISEC/cpg/files/11663656/log.txt).
[This](https://github.com/Fraunhofer-AISEC/cpg/files/11663680/code.txt) is the file I supplied as parameter. 

With `cpg-console`, the error looks slightly different: 

```
[...]
17:57:00,100 WARN  Util code.c:9574:50: Did not find a declaration for int64_t
17:57:00,102 WARN  Util code.c:9580:57: Did not find a declaration for int64_t
17:57:00,934 WARN  Util code.c:9634:59: Did not find a declaration for int64_t
18:12:59,259 INFO  MeasurementHolder TranslationManager: Translation into full graph done in 986182 ms
java.util.concurrent.ExecutionException: java.lang.StackOverflowError
        at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
        at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073)
        at Line_18.<init>(Line_18.kts:1)
java.lang.NullPointerException: Cannot invoke "Line_18.getResult()" because "this.$$earlierScripts[17]" is null
        at Line_19.<init>(Line_19.kts:1)
```

Thanks for your help!

### PR DESCRIPTION
**Pull request by KuechA**
Currently, the EOG iteration copies the state for each step in the EOG. This consumes quite some resources and it would be great to copy the objects less frequently. One idea is to copy them only when entering/exiting a new basic block and otherwise operate on the same object.

Fixes #1194

### CODE REVIEW

File: cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/helpers/EOGWorklist.kt [hunk 1]
```diff
@@ -248,9 +248,18 @@ inline fun <reified K : Node, V> iterateEOG(
     while (worklist.isNotEmpty()) {
         val (nextNode, state) = worklist.pop()
 
-        val newState = transformation(nextNode, state.duplicate(), worklist)
+        val insideBB =
+            (nextNode.nextEOG.size == 1 &&
+                nextNode.prevEOG.size == 1 &&
+                nextNode.prevEOG.first().nextEOG.size == 1)
```
Comment (oxisto) [inline cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/helpers/EOGWorklist.kt:254]: you could use `single` or `singleOrNull` instead of checking for size 1 and using first()

File: cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/helpers/EOGWorklist.kt [hunk 2]
```diff
@@ -248,9 +248,18 @@ inline fun <reified K : Node, V> iterateEOG(
     while (worklist.isNotEmpty()) {
         val (nextNode, state) = worklist.pop()
 
-        val newState = transformation(nextNode, state.duplicate(), worklist)
+        val insideBB =
```
[the remark this answers is not in the document]
Comment (KuechA) [reply cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/helpers/EOGWorklist.kt:251]: This should check if we're not near the beginning/end of a basic block (i.e., there are no merge points or branches of the EOG nearby). If that's the case, we just parse the whole basic block and do not want to duplicate the state. Near the beginning/end, we do want to copy the state to avoid terminating the iteration too early by messing up with the state-changing checks.

[the remark this answers is not in the document]
Comment (oxisto) [reply cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/helpers/EOGWorklist.kt:251]: Can you maybe add this as a comment to the variable. Otherwise it is confusing because we don’t actually do any check if we are in a compound statement or similar but it’s purely based on the “entry” within the block.

File: cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/LabelStatement.kt [hunk 3]
```diff
@@ -48,6 +50,14 @@ class LabelStatement : Statement() {
...
     }
 
+    override var statementEdges: MutableList<PropertyEdge<Statement>>
+        get() =
+            subStatement?.let { mutableListOf(PropertyEdge(this, it, mutableMapOf())) }
+                ?: mutableListOf()
+        set(value) {
+            subStatement = value.firstOrNull()?.end
+        }
+
```
Comment (oxisto) [inline cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/LabelStatement.kt:60]: I would prefer using the `wrap` / `unwrap` function instead of doing it manually, since they already do "some" magic and might do more magic in the future.

```suggestion
override var statementEdges: MutableList<PropertyEdge<Statement>>
        get() {
            return subStatement?.let { wrap(listOf(it), this) } ?: mutableListOf()
        }
        set(value) {
            subStatement = unwrap(value).firstOrNull()
        }
```

Comment (oxisto) [inline cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/statements/LabelStatement.kt:60]: I would prefer using the `wrap` / `unwrap` functions here for consistency.

```suggestion
    override var statementEdges: MutableList<PropertyEdge<Statement>>
        get() =
            subStatement?.let { mutableListOf(PropertyEdge(this, it, mutableMapOf())) }
                ?: mutableListOf()
        set(value) {
            subStatement = value.firstOrNull()?.end
        }

```

**Review by oxisto — APPROVED** [review]
