### PR TITLE
Fix DFG of the variable of a`ForEachStatement`

### LINKED ISSUE #1006: `variable` and `iterable` from `ForEachStatement` are not connected in DFG
# Unexpected behavior

When analyzing code with a for each loop, there is no dataflow from the `iterable` to the `variable` of the `ForEachStatement`. The `variable` also has `UninitializedValue` as `initializer` which might be related to the missing dataflow.

# Example

```
class For {
    public void forIterator() {
        int[] a = {1,2,3,4,5};
        for(int j : a) {
            System.out.println(j);
        }
    }
}
```

# Changes to the configuration

```
TranslationConfiguration.builder()
            .defaultPasses()
            .defaultLanguages()
            .codeInNodes(true)
```

### PR DESCRIPTION
**Pull request by KuechA**
The variable declaration in a `ForEachStatement` does not have an initializer and is therefore not really considered by the `ControlFlowSensitiveDFGPass`. We have to handle this case separately.

Closes #1006

### CODE REVIEW

**Review by oxisto — COMMENTED** [review]
Do we need to handle anything else in the normal DFG pass?

**Comment by KuechA** [comment]
No, actually, the respective edges from the `DFGPass` would probably be removed anyway... I tried an alternative approach by setting the initializer of the variable in the normal DFG Pass with the iterable but I didn't like the solution (even if it would have worked).

**Comment by oxisto** [comment]
> No, actually, the respective edges from the `DFGPass` would probably be removed anyway... I tried an alternative approach by setting the initializer of the variable in the normal DFG Pass with the iterable but I didn't like the solution (even if it would have worked).

I just meant, if the user is missing out on this "feature", if he is only using the "normal" DFG pass?

**Comment by KuechA** [comment]
> > No, actually, the respective edges from the `DFGPass` would probably be removed anyway... I tried an alternative approach by setting the initializer of the variable in the normal DFG Pass with the iterable but I didn't like the solution (even if it would have worked).
> 
> I just meant, if the user is missing out on this "feature", if he is only using the "normal" DFG pass?

Good point. Since the variable declaration is wrapped in a DeclarationStatement, the DFG edge was indeed not added only with the normal DFG pass. Btw. the `DeclarationStatement` has a DFG edge to the `ForEachStatement`. Do you have any idea why this is the case? We do not add this edge in our passes

**Comment by oxisto** [comment]
> > > No, actually, the respective edges from the `DFGPass` would probably be removed anyway... I tried an alternative approach by setting the initializer of the variable in the normal DFG Pass with the iterable but I didn't like the solution (even if it would have worked).
> > 
> > 
> > I just meant, if the user is missing out on this "feature", if he is only using the "normal" DFG pass?
> 
> Good point. Since the variable declaration is wrapped in a DeclarationStatement, the DFG edge was indeed not added only with the normal DFG pass. Btw. the `DeclarationStatement` has a DFG edge to the `ForEachStatement`. Do you have any idea why this is the case? We do not add this edge in our passes

uhm no idea :D @konradweiss ?

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.kt [hunk 1]
```diff
@@ -206,6 +207,23 @@ open class ControlFlowSensitiveDFGPass : Pass() {
...
+                        as? VariableDeclaration
+
+                writtenDecl?.let { wd ->
+                    iterable?.let { wd.addPrevDFG(it) }
+                    // Add the variable declaration to the list of previous write nodes in this path
+                    previousWrites[wd] = mutableListOf(wd)
+                }
             }
 
             // Check for loops: No loop statement with the same state as before and no write which
```
Comment (oxisto) [inline cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.kt:229]: While you are editing this file, the comment for `handleVariableDeclaration` is wrong (copy/paste) from function declaration.

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/DFGPass.kt [hunk 2]
```diff
@@ -90,6 +92,15 @@ class DFGPass : Pass() {
         }
     }
 
+    /**
+     * For a [DeclarationStatement], the whole statement flows into its declarations. This is fine
+     * because it's used as a wrapper if a Statement is needed but we only have a Declaration (which
+     * is not a statement).
+     */
+    private fun handleDeclarationStatement(node: DeclarationStatement) {
```
Comment (oxisto) [inline cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/DFGPass.kt:100]: Decision: Not handling this for *all* declaration statements, but only do this for the `ForStatement`.

Comment (KuechA) [reply cpg-core/src/main/java/de/fraunhofer/aisec/cpg/passes/DFGPass.kt]: I removed this method and handle the `ForEachStatement` differently now. @maximiliankaul please check if the new handling makes sense to you

File: cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.kt [hunk 3]
```diff
@@ -76,7 +77,7 @@ open class ControlFlowSensitiveDFGPass : Pass() {
      * Removes all the incoming and outgoing DFG edges for each variable declaration in the function
      * [node].
      */
-    private fun clearFlowsOfVariableDeclarations(node: FunctionDeclaration) {
+    private fun clearFlowsOfVariableDeclarations(node: Node) {
```
Comment (maximiliankaul) [inline cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.kt:80]: Why now `Node` instead of the `FunctionDeclaration`?  The doc string reads like this should be reverted.

File: cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.kt [hunk 4]
```diff
@@ -93,7 +94,7 @@ open class ControlFlowSensitiveDFGPass : Pass() {
      * - Assignments with an operation e.g. of the form "variable += rhs"
      * - Read operations on a variable
      */
-    private fun handleFunction(node: FunctionDeclaration) {
+    private fun handleFunction(node: Node) {
```
Comment (maximiliankaul) [inline cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.kt:97]: Why does `handleFunction` receive a `Node` instead of a `FunctionDeclaration`?

File: cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.kt [hunk 5]
```diff
@@ -208,6 +209,59 @@ open class ControlFlowSensitiveDFGPass : Pass() {
...
+            } else if (currentNode is ForEachStatement && currentNode.variable != null) {
+                // The VariableDeclaration in the ForEachStatement doesn't have an initializer, so
+                // the "normal" case won't work. We handle this case separately here...
+                // This is what we write to the declaration
+                val iterable = currentNode.iterable as? Expression
+
+                val writtenTo =
+                    when (currentNode.variable) {
+                        is DeclarationStatement ->
+                            (currentNode.variable as DeclarationStatement).singleDeclaration!!
```
Comment (maximiliankaul) [inline cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.kt:221]: I assume this works "right now", but this is broken once we have support for multiple vars (#1089). Correct?

**Review by maximiliankaul — APPROVED** [review]
I'm generally in favor of this PR. The only thing I dislike is the heavy use of `!!` in the pass.

File: cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.kt (hunk 5 above)
Comment (KuechA) [reply cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.kt:221]: That's correct. Actually, this will probably require a couple of changes in this pass (but this will depend on the implementation of course)

File: cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.kt (hunk 4 above)
Comment (KuechA) [reply cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.kt:97]: See above

File: cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.kt (hunk 3 above)
Comment (KuechA) [reply cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.kt:80]: I updated the text to fit the change. I changed it to `Node` because probably, we also want to handle blocks of code which aren't in any function but (e.g. a script)

File: cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.kt (hunk 5 above)
Comment (maximiliankaul) [reply cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.kt:221]: Let's worry about this in the future...

**Comment by oxisto** [comment]
> I'm generally in favor of this PR. The only thing I dislike is the heavy use of `!!` in the pass.

Agree. Can you change it to a local variable assignment + smart card instead? We should really avoid !!

File: cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.kt [hunk 6]
```diff
@@ -208,6 +209,59 @@ open class ControlFlowSensitiveDFGPass : Pass() {
...
+                            (currentNode.variable as DeclarationStatement).singleDeclaration
+                        else -> currentNode.variable
+                    }
+
+                // We wrote something to this variable declaration
+                writtenDecl =
+                    when (writtenTo) {
+                        is Declaration -> writtenTo
+                        is DeclaredReferenceExpression -> writtenTo.refersTo
+                        else -> null // TODO: This shouldn't happen
```
Comment (konradweiss) [inline cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/ControlFlowSensitiveDFGPass.kt:230]: Maybe not a todo, either a normal comment or a log warning IMO, what do you think? I would avoid TODO if there is nothing that we actually want to implement here. Maybe, `NOTE`

**Review by konradweiss — CHANGES_REQUESTED** [review]
