### PR TITLE
Do not resolve unqualified symbols in current record without `HasImplicitReceiver`

### LINKED ISSUE #1983: Python incorrectly resolves fields in unqualified lookup
Currently our python frontend (and probably others?) resolve fields when doing an unqualified lookup, i.e., just looking for `symbol` (but not `self.symbol`). But that is not allowed in Python (as well as in Go actually) and this leads to horrendous wrong results.

Consider the following snippet:

```Python
a = "Hello"

class MyClass:
    def foo(self):
        self.a = 1
        print(a)
```

The `a` in the print statement should resolve to the global `a`. Instead it currently resolves to the field declaration of `a`, which is only accessible through `self.a`.

This also applies to imports as well 
```Python
import os

class MyClass:
    def bar(self):
        self.os = 1
        print(os.name)
```

Here, `os` is also wrongfully resolved to `MyClass.os`.

This might be a bigger issue and effecting all language frontends that require some sort of "qualified" lookup.

### PR DESCRIPTION
**Pull request by oxisto**
We need to consider the trait `HasImplicitReceiver` (or the lack thereof) when resolving symbols in an unqualified lookup to not accidentally resolve fields/methods of a class without an receiver.

Fixes #1983

### CODE REVIEW

File: cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/scopes/Scope.kt [hunk 1]
```diff
@@ -227,6 +239,20 @@ sealed class Scope(
             list += value
         }
     }
+
+    fun firstParentOrNull(predicate: (Scope) -> Boolean): Scope? {
```
Comment (KuechA) [inline cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/scopes/Scope.kt:243]: `firstParentScopeOrNull` to not confuse it with the `astParent`?

File: cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/SymbolResolverTest.kt [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+        assertNotNull(a)
+
+        val fieldA = result.records["MyClass"]?.fields["a"]
+        assertNotNull(fieldA)
+
+        val aRefs = result.refs("a")
+        aRefs.filterIsInstance<MemberExpression>().forEach { assertRefersTo(it, fieldA) }
+        aRefs.filter { it !is MemberExpression }.forEach { assertRefersTo(it, a) }
+
+        val osRefs = result.refs("os")
```
Comment (KuechA) [inline cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/SymbolResolverTest.kt:59]: A short comment would be helpful here to understand that `os.name` does not have a reference any more because this used to be different/wrong until recently

**Review by KuechA — APPROVED** [review]

File: cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/scopes/Scope.kt (hunk 1 above)
Comment (oxisto) [reply cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/graph/scopes/Scope.kt:243]: Was my original idea as well. I can change it.

File: cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/SymbolResolverTest.kt (hunk 2 above)
Comment (oxisto) [reply cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/SymbolResolverTest.kt:59]: Well it was always wrong, but yes it makes sense to comment the unit test.

**Comment by oxisto** [comment]
After some digging, I actually discovered that we already have the opposite trait `HasImplicitReceiver`, so we should probably use the existing one instead.

File: cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/SymbolResolverTest.kt [hunk 3]
```diff
@@ -0,0 +1,72 @@
...
+                it.registerLanguage<PythonLanguage>()
+            }
+
+        val a =
+            result.namespaces["fields"]
+                .variables[{ it.name.localName == "a" && it !is FieldDeclaration }]
+        assertNotNull(a)
+
+        val fieldA = result.records["MyClass"]?.fields["a"]
+        assertNotNull(fieldA)
```
[the remark this answers is not in the document]
Comment (oxisto) [reply cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/SymbolResolverTest.kt:54]: Unncessary in this case, because we already know that fieldA is a field declaration (because `fields` returns a Field Declaration), `assertIs` is only necessary if the variable `fieldA` would be a "Node" or a "Declaration" and we want to assert its a field.

File: cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/SymbolResolverTest.kt [hunk 4]
```diff
@@ -0,0 +1,90 @@
...
+
+        val aRefs = result.refs("a")
+        aRefs.filterIsInstance<MemberExpression>().forEach { assertRefersTo(it, fieldA) }
```
[the remark this answers is not in the document]
Comment (oxisto) [reply cpg-language-python/src/test/kotlin/de/fraunhofer/aisec/cpg/frontends/python/SymbolResolverTest.kt:57]: As discussed offline. We cannot fix the `copyA = a` problem, so I adjusted this line for now and created issue https://github.com/Fraunhofer-AISEC/cpg/issues to track it.

The rest works after adjustment in the python add declaration pass, which was missing an FQN.
