### PR TITLE
Correctly setting the type of a CPP simple declaration

### LINKED ISSUE #153: TypeParser causes StringIndexOutOfBoundsException
The typeparser seems to use some fancy-magic to parse the type string looking for brackets, such as (, [, however, it seems to be missing code that handles if for some reason it cannot find the end-bracket or if multiple brackets are stacked.

Consider the following snippet:

```cpp
#define SOME_MACRO(t) t

void SomeFunction(const char* text=SOME_MACRO(""));
```

The first issue, is that the type parser seems to try to parse the complete function declaration signature to retrieve a type (probably the return type) of it. Not sure what the intent here is.

https://github.com/Fraunhofer-AISEC/cpg/blob/1024f02164d547f961c0f2f3a6d0642410ef6711/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationListHandler.java#L58-L59

Second issue is, that this will crash within the type parser, since he seems to be confused by the double `)` within the function signature.

```
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: 16
	at java.base/java.lang.StringLatin1.charAt(StringLatin1.java:48)
	at java.base/java.lang.String.charAt(String.java:709)
	at de.fraunhofer.aisec.cpg.graph.type.TypeParser.findMatching(TypeParser.java:187)
	at de.fraunhofer.aisec.cpg.graph.type.TypeParser.separate(TypeParser.java:321)
	at de.fraunhofer.aisec.cpg.graph.type.TypeParser.createFrom(TypeParser.java:648)
	at de.fraunhofer.aisec.cpg.frontends.cpp.DeclarationListHandler.handleSimpleDeclaration(DeclarationListHandler.java:58)
	at de.fraunhofer.aisec.cpg.frontends.cpp.DeclarationListHandler.lambda$new$0(DeclarationListHandler.java:48)
	at de.fraunhofer.aisec.cpg.frontends.Handler.handle(Handler.java:112)
	at de.fraunhofer.aisec.cpg.frontends.cpp.DeclarationHandler.handleSingleDeclarator(DeclarationHandler.java:199)
	at de.fraunhofer.aisec.cpg.frontends.cpp.DeclarationHandler.handleSimpleDeclaration(DeclarationHandler.java:171)
	at de.fraunhofer.aisec.cpg.frontends.cpp.DeclarationHandler.lambda$new$0(DeclarationHandler.java:53)
	at de.fraunhofer.aisec.cpg.frontends.Handler.handle(Handler.java:112)
	at de.fraunhofer.aisec.cpg.frontends.cpp.DeclarationHandler.handleTranslationUnit(DeclarationHandler.java:261)
	at de.fraunhofer.aisec.cpg.frontends.cpp.CXXLanguageFrontend.parse(CXXLanguageFrontend.java:218)
	at de.fraunhofer.aisec.cpg.TranslationManager.runFrontends(TranslationManager.java:196)
	at de.fraunhofer.aisec.cpg.TranslationManager.lambda$analyze$0(TranslationManager.java:90)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1771)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1763)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
```

### PR DESCRIPTION
**Pull request by oxisto**
This sets the type of a CPP simple declaration according to its declspecifier instead of the raw signature.

This partially fixes #153. It will not occur that often now probably but the core issue is still there.

### CODE REVIEW

**Comment by oxisto** [comment]
*sigh*, looks like the internal `IASTDeclSpecifier` class gets rid of the pointer in the type for some reason, so this is not good :(

**Comment by oxisto** [comment]
I have added additional logic, that is also applied in other cases it seems to "clean" the type string before handing it to the type parser. This addresses this issue for now but it could still potentially creep up.

**Comment by oxisto** [comment]
Back to using the decl-specifier, "enriched" with the information given in the declarator, i.e. pointer and array types. Way less hacky than before.

File: src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationHandler.java [hunk 1]
```diff
@@ -325,4 +327,27 @@ TranslationUnitDeclaration handleTranslationUnit(CPPASTTranslationUnit translati
...
+
+    // append names, pointer operators and array modifiers and such
+    for (IASTNode node : declarator.getChildren()) {
+      if (node instanceof IASTPointerOperator || node instanceof IASTArrayModifier) {
+        typeString.append(node.getRawSignature());
+      }
+    }
+
+    return typeString.toString();
+  }
```
Comment (vfsrfs) [inline src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationHandler.java:352]: This seems to be less-error-prone than using `ctx.getRawSignature` for most cases. Nonetheless, we have a problem with function pointers, as by using this method to determine the raw type string instead of using `ctx.getRawSignature`, the fptr `void ((*single_param)(int))` is transformed into `void`. This is not the intended behaviour, since fptrs are addressed by their own type.

Comment (oxisto) [reply src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationHandler.java:352]: That is why this is not used for function pointers (yet)

Basically function pointers are handled (for some reason) here:

https://github.com/Fraunhofer-AISEC/cpg/blob/8ff74381b5a2a753727da2eb4db890f79024c84a/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationListHandler.java#L67-L68

I can add a comment to make it more clear

File: src/main/java/de/fraunhofer/aisec/cpg/graph/type/TypeParser.java [hunk 2]
```diff
@@ -180,6 +204,11 @@ private static int findMatching(char openBracket, char closeBracket, String stri
     int i = 0;
 
     while (counter != 0) {
+      if (i >= string.length()) {
+        // dirty hack for now
+        return string.length();
+      }
+
```
[the remark this answers is not in the document]
Comment (oxisto) [reply src/main/java/de/fraunhofer/aisec/cpg/graph/type/TypeParser.java:211]: Sure, feel free to adjust this PR

File: src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationHandler.java (hunk 1 above)
Comment (vfsrfs) [reply src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationHandler.java:352]: Yes I have seen that if and that should be correct. However I tested the following snippet and I 
reached this code here: [https://github.com/Fraunhofer-AISEC/cpg/blob/8ff74381b5a2a753727da2eb4db890f79024c84a/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationHandler.java#L107](https://github.com/Fraunhofer-AISEC/cpg/blob/8ff74381b5a2a753727da2eb4db890f79024c84a/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationHandler.java#L107)
```
int main(){
void ((*single_param)(int));
}
```

Comment (vfsrfs) [reply src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationHandler.java:352]: In that case apparently the code is treated as a VariableDeclaration and therefore the if statement is true.

Comment (oxisto) [reply src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationHandler.java:352]: Can you add this snippet somewhere to the existing function pointer unit tests. You can deliberately make the unit test fail and then I can have a look.

Comment (konradweiss) [reply src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationHandler.java:352]: > Can you add this snippet somewhere to the existing function pointer unit tests including an assert on how the type should be parsed. You can deliberately make the unit test fail and then I can have a look.

Ok I looked through the PR, and will await until you took that look.

Comment (vfsrfs) [reply src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/DeclarationHandler.java:352]: Yes I will add the snippet to a test

**Comment by vfsrfs** [comment]
I have added the snippet and a test, which is failing due to the usage of `getTypeStringFromDeclarator`

**Comment by oxisto** [comment]
You made it fail! ;) Thanks, I will look into it.

**Comment by oxisto** [comment]
Ok looks like there are some more issues that creep up here. I have adjusted the test file to contain two different function pointers each on global and local scope:
```
void ((*global_single_param)(int));
int (*global_two_param)(int, unsigned long);

int main() {
  void ((*local_single_param)(int));
  int (*local_two_param)(int, unsigned long);
}
```

Now the "original" problem was, that your function pointer `local_single_param` was nested in "()" and we do not handle those very well. In fact, `DeclarationHandler::handleFunctionPointer` was never called and it was just treated as a regular variable and things went wrong. So I am not sure if we want to actually fix this in this PR, but we do not handle nested declarators very well at the moment. This is not specific to just function pointers. The `local_two_param` gets parsed correctly (including its type).

The second issue is, that while the `global_two_param` function pointer is parsed correctly (including its type), it is - for some reason - being parsed as a `FieldDeclaration`, so it seems we have another issue where global function pointers are parsed as field declarations.

Lastly, is it intended, that the function pointer type has an empty name, @vfsrfs?  Wouldn't it make sense to set the signature as name? This is how clang does it for example:

```
|-VarDecl 0x7fe6e5070d28 <types/fptr_type.cpp:1:1, col:27> col:9 single_param 'void ((*)(int))'
`-VarDecl 0x7fe6e5070ff0 <line:2:1, col:35> col:7 intFptr1 'int (*)(int, unsigned long)'
```

**Comment by oxisto** [comment]
I fixed the aforementioned issues with function pointer types, all tests should run now.

I think it would still be better to parse the function pointer type in the `handleSimpleDeclaration` by going downwards into the decl-specifiers and declarator and see whether we can re-construct them in the correct order for the function type, rather than going upwards from the declarator and use the raw string, but that is the way it is for now.

I left this comment in the code as well for future discussions.

File: src/main/java/de/fraunhofer/aisec/cpg/graph/type/TypeParser.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (konradweiss) [reply src/main/java/de/fraunhofer/aisec/cpg/graph/type/TypeParser.java:211]: @vfsrfs @oxisto can one of you resolve this if it is still relevant? Then we can merge

[the remark this answers is not in the document]
Comment (oxisto) [reply src/main/java/de/fraunhofer/aisec/cpg/graph/type/TypeParser.java:211]: I would suggest a merge now and then @vfsrfs can see afterwards if any more issues creep up. The PR already fixed way more bugs than it intended to ;)
