### PR TITLE
Fix CDG for ShortCircuitOperators

### LINKED ISSUE #2486: CDG and ShortCircuitOperators
```
foo() && bar()
```

one would expect `prevCDG(bar())` to contain `foo()` but this is not the case.
(Tested with a language that has `HasShortCircuitOperator`. The `&&` correctly translates to a `ShortCircuitOpertor` node.)

Problem identified by @lshala and @morbitzer

### PR DESCRIPTION
**Pull request by maximiliankaul**
Fixes #2486

### CODE REVIEW

File: cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/BasicBlockCollectorPass.kt [hunk 1]
```diff
@@ -95,9 +103,30 @@ class BasicBlockCollectorPass(ctx: TranslationContext) : EOGStarterPass(ctx) {
                         }
                     }
             }
+
             basicBlock.nodes.add(currentStartNode)
 
-            val nextRelevantEOGEdges = currentStartNode.nextEOGEdges
+            // Note: This may not identify all cases correctly, e.g., if a ShortCircuitOperator is
+            // not the direct astParent.
+            val shortCircuit = currentStartNode.astParent as? ShortCircuitOperator
```
Comment (KuechA) [inline cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/BasicBlockCollectorPass.kt:116]: Would it be better to make the look-ahead in the EOG here instead of checking the `astParent`?

Comment (maximiliankaul) [reply cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/BasicBlockCollectorPass.kt:116]: I'll try that.

Comment (maximiliankaul) [reply cpg-core/src/main/kotlin/de/fraunhofer/aisec/cpg/passes/BasicBlockCollectorPass.kt:116]: Merging this now as is. Future work in https://github.com/Fraunhofer-AISEC/cpg/issues/2539
