### PR TITLE
Fix for null annotations

### LINKED ISSUE #192: Field `annotations` must not be null, breaks OGM
Commit 7d56eda487e8ec408b13036581d08b5e9800ff3e breaks the object graph mapper (OGM) of Codyze (and possibly Neo4J) and makes CPG structure ambiguous.

Collection fields of `Node`s must not be null.

Fields of classes in the CPG structure will result in either _edges_ or _properties_  of a node. The clearest way is to make that explicit by using the `@Relationship` annotation to enforce an edge. If that is not present, the OGM will investigate the value of the respective field and see if it is a `Node` type or Collection of `Node`s. This requires the field to be non-null, otherwise the OGM will consider it a property on the one hand, but not be able to provide type information on the other hand.

In its current form, Codyze will run into many `IllegalStateException`s.

### PR DESCRIPTION
**Pull request by JulianSchuette**
Fixes #192

### CODE REVIEW

**Comment by oxisto** [comment]
My original though was to set it to `null` to avoid creation of many list objects in the in-memory graph if the annotation processing feature is turned off. Can you give an example of the `IllegalStateException`s that codyze gives? I was under the impression that I "fixed" this in https://github.com/Fraunhofer-AISEC/codyze/pull/41

File: src/main/java/de/fraunhofer/aisec/cpg/graph/Node.java [hunk 1]
```diff
@@ -116,7 +120,7 @@
 
   /** List of annotations associated with that node. */
   @SubGraph("AST")
-  protected List<Annotation> annotations;
+  public List<Annotation> annotations = new ArrayList<>();
```
Comment (oxisto) [inline src/main/java/de/fraunhofer/aisec/cpg/graph/Node.java:123]: Why is this member public?

File: src/main/java/de/fraunhofer/aisec/cpg/graph/Node.java [hunk 2]
```diff
@@ -259,6 +267,15 @@ public boolean isImplicit() {
     return this.implicit;
   }
 
+  @NonNull
+  public List<Annotation> getAnnotations() {
+    return annotations;
+  }
+
+  public void setAnnotations(@NonNull List<Annotation> annotations) {
```
Comment (oxisto) [inline src/main/java/de/fraunhofer/aisec/cpg/graph/Node.java:275]: The only issue that I have with this, is that we create two list for each node, if `processAnnotations` is enabled. Once for each node in the init and another one in the `CXXLanguageFrontend::handleAttributes` function which is then used in this setter here. We should probably follow a similar pattern like the DFG and EOG properties that *add* to it (or clear it) rather than creating a new list.

Comment (JulianSchuette) [reply src/main/java/de/fraunhofer/aisec/cpg/graph/Node.java:275]: Agree, re-creating the collections is not expensive, but we should keep it consistent and possibly even make collection fields `final`  one day.

File: src/main/java/de/fraunhofer/aisec/cpg/graph/Node.java (hunk 1 above)
Comment (JulianSchuette) [reply src/main/java/de/fraunhofer/aisec/cpg/graph/Node.java:123]: All members are public to allow reflection access from outside of the module without having to use `--add-opens` workarounds in Java >= 9.

Comment (oxisto) [reply src/main/java/de/fraunhofer/aisec/cpg/graph/Node.java:123]: All the other members are protected?

Comment (JulianSchuette) [reply src/main/java/de/fraunhofer/aisec/cpg/graph/Node.java]: Err... Anyway, it's now consistent with the other fields :-)
