### PR TITLE
Major refactoring: Strict separation of language frontends from later stages

### LINKED ISSUE #59: Passes get the last LanguageFrontend that was created.
`
      // Set frontend so passes know what language they are working on.
      for (Pass pass : config.getRegisteredPasses()) {
        pass.setLang(frontend);
      }
`
This is executed at the end of `runFrontends` with frontend being set in the loop that executes the frontends on the files. Therefore only the last frontend is set to all passes.
This can stay as long as frontends are static in relation to the processed files (no TranslationUnit dependent state is internally stored), but will have to change as soon as we allow the analysis of code that uses different Frontends.

### LINKED ISSUE #691: ThreadSafe TypeManager
Currently the TypeManager is implemented as Singleton Object. This causes some problems when trying to use the API in a multi-threaded manner.
```
Caused by: java.lang.NullPointerException: Cannot invoke "de.fraunhofer.aisec.cpg.frontends.LanguageFrontend.getScopeManager()" because "this.frontend" is null
	at de.fraunhofer.aisec.cpg.graph.TypeManager.getCommonType(TypeManager.java:446)
	at de.fraunhofer.aisec.cpg.graph.TypeManager.isSupertypeOf(TypeManager.java:570)
	at de.fraunhofer.aisec.cpg.graph.statements.expressions.CastExpression.typeChanged(CastExpression.java:85)
	at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.lambda$refreshType$12(Expression.java:244)
	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
	at de.fraunhofer.aisec.cpg.graph.statements.expressions.Expression.refreshType(Expression.java:242)
	at de.fraunhofer.aisec.cpg.helpers.SubgraphWalker.refreshType(SubgraphWalker.java:219)
	at de.fraunhofer.aisec.cpg.helpers.SubgraphWalker.refreshType(SubgraphWalker.java:216)
	at de.fraunhofer.aisec.cpg.helpers.SubgraphWalker.refreshType(SubgraphWalker.java:216)
	at de.fraunhofer.aisec.cpg.helpers.SubgraphWalker.refreshType(SubgraphWalker.java:216)
	at de.fraunhofer.aisec.cpg.helpers.SubgraphWalker.refreshType(SubgraphWalker.java:216)
	at de.fraunhofer.aisec.cpg.helpers.SubgraphWalker.refreshType(SubgraphWalker.java:216)
	at de.fraunhofer.aisec.cpg.helpers.SubgraphWalker.refreshType(SubgraphWalker.java:216)
	at de.fraunhofer.aisec.cpg.helpers.SubgraphWalker.refreshType(SubgraphWalker.java:216)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1087)
	at de.fraunhofer.aisec.cpg.passes.TypeHierarchyResolver.accept(TypeHierarchyResolver.java:95)
	at de.fraunhofer.aisec.cpg.passes.TypeHierarchyResolver.accept(TypeHierarchyResolver.java:55)
	at de.fraunhofer.aisec.cpg.TranslationManager.analyze$lambda-2(TranslationManager.kt:96)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1764)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1756)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpAsyncBlocker(ForkJoinPool.java:1145)
	at java.base/java.util.concurrent.ForkJoinPool.helpAsyncBlocker(ForkJoinPool.java:3160)
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1924)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2085)
```

I think the conventional fix would be to add a _synchronized_ qualifier to getInstance(). A more efficient way (but maybe "polluting") is to keep a ThreadLocal storage with an instance per thread.

### LINKED ISSUE #953: Remove access to `LanguageFrontend` in passes
A `LanguageFrontend` should only exist during parsing, however we use it currently in a very hacky way to transfer certain information to the passes. We should extract these information needed into a new class (e.g. `LanguageFeatures`) and make this available to every node. This would also solve certain issues with multi-language projects.

### PR DESCRIPTION
**Pull request by KuechA**
This PR is a *major* refactoring of a lot of core concepts in the CPG evolving around language parsing and the way passes interact with language (frontends).

## Introduction of `Language` and removal of `LanguageFrontend` from passes

We introduce a new class `Language`, which holds all meta-data information about a programming language, e.g., its name, namespace information, `LanguageTraits`. Each created `Node` has an information about its current language in the `language` property. For details please refer to the [specification](https://github.com/Fraunhofer-AISEC/cpg/blob/2c8c258bc5ddf9a835a7358da1748479ca5bb5bf/cpg-core/specifications/language.md).

This allows us now to restrict the life-cycle of a `LanguageFrontend` to the translation phase of the CPG. That means, that no `Pass` has access to a language frontend anymore and all weird code like `lang instance CXXLanguageFrontend` disappears. Instead, the language traits of each processed node's `Language` are used to fine tune things like call resolution.

## Remove of `LanguageFrontend` from `TypeManager`

The `TypeManager` (and the `TypeParser` by extension), even though it is a singleton, was using the "current" language frontend to make certain type decisions. This has been remove and the appropriate functions need to supply a `Language`, either directly or though a provider (see below).

## Introduction of the `MetadataProvider` concept

Because we have many information that we need to set in a node as soon as possible, we introduce a new concept called `MetadataProvider`. This parent interface and its derived interfaces, can be implemented by suitable classes, such as language frontends and handlers to provide additional context in the node creation. Currently, the following providers exist:
* `LanguageProvider` to set a node's language based on the current language, e.g., in the language frontend
* `ScopeProvider` to set a node's scope, e.g., based on information of the `ScopeManager`
* `CodeAndLocation` to set a node's code and location
* `IsInferredProvider` to mark a node as inferred

This system is extensible to future providers. When language frontends or handlers use the node builder functions to create nodes, a call to `Node.applyMetadata` will fetch the information of the current provider and inject it into the nodes.

## Other changes

We converted a lot of classes to Kotlin, where it made sense.

Fixes #953
Fixes #59
Fixes #691
This will definitely trigger a new major version.

### CODE REVIEW

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CLanguage.kt [hunk 1]
```diff
@@ -26,20 +26,27 @@
...
+class CLanguage :
+    Language<CXXLanguageFrontend>(),
+    HasStructs,
+    HasFunctionPointers,
+    HasQualifier,
+    HasElaboratedTypeSpecifier {
     // TODO: Shouldn't there also be the "h" ending?
     override val fileExtensions: List<String>
-        get() = listOf("c")
+        get() = listOf("c", "h")
```
Comment (oxisto) [inline cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CLanguage.kt:41]: I thought we excluded header files on purpose because otherwise they will get parsed twice if they are also included in the C files?

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/TypeManager.java [hunk 2]
```diff
@@ -317,7 +296,7 @@ public void setLanguageFrontend(@NotNull LanguageFrontend frontend) {
   }
 
   public boolean isPrimitive(Type type) {
-    return primitiveTypeNames.contains(type.getTypeName());
+    return getLanguage().getPrimitiveTypes().contains(type.getTypeName());
```
Comment (oxisto) [inline cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/TypeManager.java:299]: Can we add language as an additional parameter here? I want to get rid of the `getLanguage` calls in the singleton type manager.

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/types/TypeParser.java [hunk 3]
```diff
@@ -196,15 +162,8 @@ public static boolean isStorageSpecifier(String specifier) {
...
-    // TODO: Convert to language trait
-    if (getLanguage() instanceof JavaLanguage) {
-      return qualifier.equals(FINAL_QUALIFIER) || qualifier.equals(VOLATILE_QUALIFIER);
-    } else {
-      return qualifier.equals(CONST_QUALIFIER)
-          || qualifier.equals(VOLATILE_QUALIFIER)
-          || qualifier.equals(RESTRICT_QUALIFIER)
-          || qualifier.equals(ATOMIC_QUALIFIER);
-    }
+    return getLanguage() instanceof HasQualifier
```
Comment (oxisto) [inline cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/types/TypeParser.java:165]: Can we add language as an additional parameter here? I want to get rid of the `getLanguage` calls in the singleton type manager.

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/types/TypeParser.java [hunk 4]
```diff
@@ -216,14 +175,10 @@ protected static boolean isQualifierSpecifier(String qualifier) {
...
   public static boolean isElaboratedTypeSpecifier(String specifier) {
-    if (getLanguage() instanceof CLanguage || getLanguage() instanceof CPPLanguage) {
-      return specifier.equals(ELABORATED_TYPE_CLASS)
-          || specifier.equals(ELABORATED_TYPE_STRUCT)
-          || specifier.equals(ELABORATED_TYPE_UNION)
-          || specifier.equals(ELABORATED_TYPE_ENUM);
-    }
-
-    return false;
+    return getLanguage() instanceof HasElaboratedTypeSpecifier
```
Comment (oxisto) [inline cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/types/TypeParser.java:178]: Can we add language as an additional parameter here? I want to get rid of the `getLanguage` calls in the singleton type manager.

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/types/TypeParser.java [hunk 5]
```diff
@@ -319,7 +275,7 @@ private static String fixGenerics(@NotNull String type) {
        * by the elaborate type specifier and at least one more horizontal whitespace, which marks
        * that it is indeed an elaborate type and not something like structMy.
        */
-      for (String elaborate : elaboratedTypes) {
+      for (String elaborate : ((CPPLanguage) getLanguage()).getElaboratedTypeSpecifier()) {
```
Comment (oxisto) [inline cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/types/TypeParser.java:278]: Can we add language as an additional parameter here? I want to get rid of the `getLanguage` calls in the singleton type manager.

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/types/TypeParser.java [hunk 6]
```diff
@@ -598,7 +554,7 @@ private static List<String> joinPrimitive(@NotNull List<String> typeBlocks) {
     boolean foundPrimitive = false;
 
     for (String s : typeBlocks) {
-      if (PRIMITIVES.contains(s)) {
+      if (getLanguage().getPrimitiveTypes().contains(s)) {
```
Comment (oxisto) [inline cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/types/TypeParser.java:557]: Can we add language as an additional parameter here? I want to get rid of the `getLanguage` calls in the singleton type manager.

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CLanguage.kt (hunk 1 above)
Comment (KuechA) [reply cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CLanguage.kt:41]: Hmmm, I don't know about that but one test failed when it wasn't included because it didn't know which frontend was responsible for the header file.

Comment (oxisto) [reply cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CLanguage.kt:41]: Looks like the old frontend also included it.

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/TranslationManager.kt [hunk 7]
```diff
@@ -418,3 +405,19 @@ private constructor(
         }
     }
 }
+
+object AnyLanguage : Language<LanguageFrontend>() {
```
Comment (oxisto) [inline cpg-core/src/main/java/de/fraunhofer/aisec/cpg/TranslationManager.kt:409]: Can be removed I guess.

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/Handler.java [hunk 8]
```diff
@@ -171,4 +177,17 @@ private Class<?> getBaseClass(Type type) {
 
     return null;
   }
+
+  public @NotNull L getFrontend() {
```
Comment (oxisto) [inline cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/Handler.java:181]: doc

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/Handler.java [hunk 9]
```diff
@@ -171,4 +177,17 @@ private Class<?> getBaseClass(Type type) {
...
+    return frontend;
+  }
+
+  public @NotNull Language<L> getLanguage() {
```
Comment (oxisto) [inline cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/Handler.java:185]: doc

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/Language.kt [hunk 10]
```diff
@@ -0,0 +1,64 @@
...
+ *
+ * Furthermore, since this also implements [Node], one node for each programming language used is
+ * persisted in the final graph (database) and each node links to its corresponding language using
+ * the [Node.language] property.
+ */
+abstract class Language<T : LanguageFrontend> : Node() {
+    /** The file extensions without the dot */
+    abstract val fileExtensions: List<String>
+
+    abstract val namespaceDelimiter: String
```
Comment (oxisto) [inline cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/Language.kt:45]: doc

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/Language.kt [hunk 11]
```diff
@@ -0,0 +1,64 @@
...
+
+    abstract val frontend: Class<out T>
```
Comment (oxisto) [inline cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/Language.kt:47]: doc

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/Language.kt [hunk 12]
```diff
@@ -0,0 +1,64 @@
...
+
+    open val primitiveTypes: Set<String>
```
Comment (oxisto) [inline cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/Language.kt:49]: doc

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/Language.kt [hunk 13]
```diff
@@ -0,0 +1,64 @@
...
+        get() = setOf("byte", "short", "int", "long", "float", "double", "boolean", "char")
+
+    abstract fun newFrontend(
```
Comment (oxisto) [inline cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/Language.kt:52]: doc

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/Language.kt [hunk 14]
```diff
@@ -0,0 +1,64 @@
...
+        config: TranslationConfiguration,
+        scopeManager: ScopeManager = ScopeManager()
+    ): T
+
+    fun handlesFile(file: File): Boolean {
```
Comment (oxisto) [inline cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/Language.kt:57]: doc

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageFrontend.java [hunk 15]
```diff
@@ -26,121 +26,50 @@
...
-import java.util.function.BiConsumer;
-import java.util.function.BiPredicate;
 import org.apache.commons.lang3.StringUtils;
 import org.jetbrains.annotations.NotNull;
 import org.jetbrains.annotations.Nullable;
 import org.slf4j.Logger;
 import org.slf4j.LoggerFactory;
 
-public abstract class LanguageFrontend {
+public abstract class LanguageFrontend extends ProcessedListener
```
Comment (oxisto) [inline cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageFrontend.java:44]: This class should also have a quick javadoc explaining what it does and what it NOT does and how long the lifecycle of it is.

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageFrontend.java [hunk 16]
```diff
@@ -26,121 +26,50 @@
...
-   */
-  protected Map<Object, BiConsumer<Object, Object>> objectListeners = new HashMap<>();
-
-  protected Map<BiPredicate<Object, Object>, BiConsumer<Object, Object>> predicateListeners =
-      new HashMap<>();
-  protected Map<Object, Object> processedMapping = new HashMap<>();
   private final String namespaceDelimiter;
   protected TranslationUnitDeclaration currentTU = null;
 
   // Todo Moving this to scope manager and add listeners and processedMappings to specified scopes.
```
Comment (oxisto) [inline cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageFrontend.java:59]: I think this todo is done

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageFrontend.java [hunk 17]
```diff
@@ -26,121 +26,50 @@
...
-   * node they are saved under get an entry in processedMapping. THis combination allows to keep the
-   * information on which AST-Node build which CPG-Node and operate with these associations once
-   * they exist, important to resolve connections between labels and label usages.
-   */
-  protected Map<Object, BiConsumer<Object, Object>> objectListeners = new HashMap<>();
-
-  protected Map<BiPredicate<Object, Object>, BiConsumer<Object, Object>> predicateListeners =
-      new HashMap<>();
-  protected Map<Object, Object> processedMapping = new HashMap<>();
   private final String namespaceDelimiter;
```
Comment (oxisto) [inline cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageFrontend.java:56]: can be removed? is now part of language.

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageFrontend.java (hunk 15 above)
Comment (oxisto) [reply cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageFrontend.java:44]: While we are at it: Convert to Kotlin?

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageTraits.kt [hunk 18]
```diff
@@ -43,3 +44,68 @@ interface HasTemplates : LanguageTrait
...
  */
 interface HasDefaultArguments : LanguageTrait
+
+/**
+ * A language trait that specifies that this language has a complex call resolution that we need to
+ * fine-tune in the language implementation.
+ */
+interface HasComplexCallResolution : LanguageTrait {
+    // TODO: better name?
+    fun doBetterCallResolution()
```
Comment (oxisto) [inline cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageTraits.kt:54]: Are we using this yet? How are we handling the former `is CXXLanguageFrontend` calls now?

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/ProcessedListener.kt [hunk 19]
```diff
@@ -0,0 +1,106 @@
...
+ *
+ */
+package de.fraunhofer.aisec.cpg.frontends
+
+import de.fraunhofer.aisec.cpg.graph.statements.GotoStatement
+import de.fraunhofer.aisec.cpg.graph.statements.LabelStatement
+import java.util.function.BiConsumer
+import java.util.function.BiPredicate
+
+open class ProcessedListener {
```
Comment (oxisto) [inline cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/ProcessedListener.kt:33]: doc

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CLanguage.kt [hunk 20]
```diff
@@ -0,0 +1,57 @@
...
+import de.fraunhofer.aisec.cpg.passes.scopes.ScopeManager
+
+/** The C language. */
+class CLanguage :
+    Language<CXXLanguageFrontend>(),
+    HasStructs,
+    HasFunctionPointers,
+    HasQualifier,
+    HasElaboratedTypeSpecifier {
+    // TODO: Shouldn't there also be the "h" ending?
```
Comment (oxisto) [inline cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CLanguage.kt:39]: Remove TODO

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageTraits.kt [hunk 21]
```diff
@@ -43,3 +44,68 @@ interface HasTemplates : LanguageTrait
...
+interface HasQualifier : LanguageTrait {
+    /** The qualifiers which exist in the language. */
+    val qualifiers: List<String>
+}
+
+/**
+ * A language trait, that specifies that this language has "elaborated type specifiers". If so, we
+ * should consider them when parsing the types.
+ */
+interface HasElaboratedTypeSpecifier : LanguageTrait {
```
Comment (oxisto) [inline cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageTraits.kt:101]: Isn't this very C++ specific?

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageTraits.kt [hunk 22]
```diff
@@ -43,3 +44,68 @@ interface HasTemplates : LanguageTrait
...
+    val elaboratedTypeSpecifier: List<String>
+}
+
+/**
+ * A language trait, that specifies that this language has specifiers which let us conclude that we
+ * do not know the type. If so, we should consider them when parsing the types.
+ */
+interface HasUnknownType : LanguageTrait {
```
Comment (oxisto) [inline cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageTraits.kt:109]: Do you mean something like `auto` or `var`? This is different from an unknown type I would say.

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/ProcessedListener.kt (hunk 19 above)
Comment (KuechA) [reply cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/ProcessedListener.kt:33]: I don't know what it does or why we need it, I just copied the code :D

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageTraits.kt (hunk 22 above)
Comment (KuechA) [reply cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageTraits.kt:109]: Yes, that's what I mean. I'm open for better names

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageTraits.kt (hunk 18 above)
Comment (KuechA) [reply cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageTraits.kt:54]: We do not use it yet. The problem is that there are many methods which are Cpp specific. So, we either need multiple such "do it better" methods or to distinguish the cases in the method. We also have to check which arguments the methods need.

The current check is either `is CPPLanguage` or `is HasComplexCallResolution`.

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/TranslationManager.kt [hunk 23]
```diff
@@ -173,8 +169,8 @@ private constructor(
                     } else {
                         if (
                             useParallelFrontends &&
-                                Util.getExtension(file).frontendClass?.simpleName ==
-                                    "GoLanguageFrontend"
+                                // TODO: This shouldn't happen in the future!
```
[the remark this answers is not in the document]
Comment (KuechA) [reply cpg-core/src/main/java/de/fraunhofer/aisec/cpg/TranslationManager.kt:171]: I added a class annotation

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/TranslationManager.kt [hunk 24]
```diff
@@ -285,8 +280,11 @@ private constructor(
             }
         }
 
-        originalScopeManager.mergeFrom(parallelScopeManagers)
-        usedFrontends.forEach { it.scopeManager = originalScopeManager }
+        // We want to merge everything into the final scope manager of the result
+        result.scopeManager.mergeFrom(parallelScopeManagers)
+
+        // TODO: remove once we got rid of all legacy stuff
+        usedFrontends.forEach { it.scopeManager = result.scopeManager }
```
[the remark this answers is not in the document]
Comment (KuechA) [reply cpg-core/src/main/java/de/fraunhofer/aisec/cpg/TranslationManager.kt:286]: Some tests fail without the code

File: cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonLanguage.kt [hunk 25]
```diff
@@ -0,0 +1,46 @@
...
+import de.fraunhofer.aisec.cpg.TranslationConfiguration
+import de.fraunhofer.aisec.cpg.frontends.Language
+import de.fraunhofer.aisec.cpg.passes.scopes.ScopeManager
+
+/** The Python language. */
+@OptIn(ExperimentalPython::class)
+class PythonLanguage : Language<PythonLanguageFrontend>() {
+    override val fileExtensions = listOf("py")
+    override val namespaceDelimiter = "."
+    override val frontend = PythonLanguageFrontend::class.java
```
Comment (maximiliankaul) [inline cpg-language-python/src/main/kotlin/de/fraunhofer/aisec/cpg/frontends/python/PythonLanguage.kt:38]: Shouldn't this be `KClass`?

File: build.gradle.kts [hunk 26]
```diff
@@ -173,7 +173,7 @@ subprojects {
     tasks.withType<KotlinCompile> {
         kotlinOptions {
             jvmTarget = "11"
-            freeCompilerArgs = listOf("-opt-in=kotlin.RequiresOptIn")
+            freeCompilerArgs = listOf("-opt-in=kotlin.RequiresOptIn", "-Xcontext-receivers")
```
Comment (oxisto) [inline build.gradle.kts:176]: This is not needed anymore

File: cpg-core/specifications/languageFrontendEnd.md [hunk 27]
```diff
@@ -0,0 +1,33 @@
...
+* HasFunctionPointers
+* HasTemplates (already exists as language trait)
+
+## Which functionality is required?
+* Customizing call resolution => Finetune function which depends on the language frontend used.
+* Language class decides which language frontend should be used
+
+
+## Other related tasks:
+* Removes typedefs from the ScopeManager
```
Comment (oxisto) [inline cpg-core/specifications/languageFrontendEnd.md:33]: This was not needed anymore, instead the special `createFrom` that was already (only) used by the cxx frontend is basically the only one which can create typedefs.

File: cpg-core/specifications/languageFrontendEnd.md [hunk 28]
```diff
@@ -0,0 +1,33 @@
...
+## Which information is required?
+* Namespace delimiter
+* Are default arguments supported?
+* Superclass keyword
+* HasClass, HasStruct (used for inference)
+* HasFunctionPointers
+* HasTemplates (already exists as language trait)
+
+## Which functionality is required?
+* Customizing call resolution => Finetune function which depends on the language frontend used.
```
Comment (oxisto) [inline cpg-core/specifications/languageFrontendEnd.md:28]: Currently not implemented, but the (empty) interface is already there.

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/SupportsParallelParsing.kt [hunk 29]
```diff
@@ -0,0 +1,31 @@
...
+ *                   $$ |      $$$$$$$  |$$ |$$$$\
+ *                   $$ |      $$  ____/ $$ |\_$$ |
+ *                   $$ |  $$\ $$ |      $$ |  $$ |
+ *                   \$$$$$   |$$ |      \$$$$$   |
+ *                    \______/ \__|       \______/
+ *
+ */
+package de.fraunhofer.aisec.cpg.frontends
+
+/** Determines if the LanguageFrontend can parse multiple files in parallel. Defaults to true. */
```
Comment (oxisto) [inline cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/SupportsParallelParsing.kt:28]:
```suggestion
/** Determines if the [LanguageFrontend] can parse multiple files in parallel. Defaults to true. */
```

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguage.kt [hunk 30]
```diff
@@ -0,0 +1,61 @@
...
+open class JavaLanguage :
+    Language<JavaLanguageFrontend>(),
+    // HasComplexCallResolution,
+    HasClasses,
+    HasSuperclasses,
+    // HasTemplates,
+    HasQualifier,
+    HasUnknownType {
+    override val fileExtensions: List<String>
+        get() = listOf("java")
```
Comment (oxisto) [inline cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/java/JavaLanguage.kt:43]: can be shortened without the get

File: cpg-core/specifications/languageFrontendEnd.md (hunk 28 above)
Comment (KuechA) [reply cpg-core/specifications/languageFrontendEnd.md:28]: In fact, I moved some parts of the code to `CPPLanguage` but I'm not sure if this would work for other relevant cases as well.

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageTraits.kt (hunk 22 above)
Comment (oxisto) [reply cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageTraits.kt:144]: OK I guess its not 100 % the same as a truly unknown type because we cannot see its declaration, etc. but we will currently treat it as such for legacy reasons.

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CPPLanguage.kt [hunk 31]
```diff
@@ -0,0 +1,315 @@
...
+    Language<CXXLanguageFrontend>(),
+    HasDefaultArguments,
+    HasTemplates,
+    HasComplexCallResolution,
+    HasStructs,
+    HasClasses,
+    HasFunctionPointers,
+    HasQualifier,
+    HasElaboratedTypeSpecifier {
+    override val fileExtensions = listOf("cpp", "cc", "hpp")
```
Comment (maximiliankaul) [inline cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CPPLanguage.kt:55]:
```suggestion
    override val fileExtensions = listOf("cpp", "cc", "cxx", "hpp", "hh")
```

File: cpg-core/specifications/language.md [hunk 32]
```diff
@@ -0,0 +1,33 @@
+# Specification: Language and Language Frontends
```
Comment (maximiliankaul) [inline cpg-core/specifications/language.md:1]: How do we make sure that people will find this documentation? Having multiple locations for documentation could be confusing...
- Include a hint in the readme file?
- and / or include this (somehow) in the generated documentation

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/types/TypeParser.java [hunk 33]
```diff
@@ -47,75 +48,23 @@ public class TypeParser {
...
-          "i128",
-          "half",
-          "bfloat",
-          "fp128",
-          "x86_fp80",
-          "ppc_fp128");
+
   private static final Pattern functionPtrRegex =
       Pattern.compile(
           "(?:(?<functionptr>[\\h(]+[a-zA-Z0-9_$.<>:]*\\*\\h*[a-zA-Z0-9_$.<>:]*[\\h)]+)\\h*)(?<args>\\(+[a-zA-Z0-9_$.<>,\\*\\&\\h]*\\))");
```
Comment (maximiliankaul) [inline cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/types/TypeParser.java:54]: What is this? Shouldn't this be a Language trait? And some documentation would be nice. regex101.com can't parse this regex...

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/types/TypeParser.java [hunk 34]
```diff
@@ -47,75 +48,23 @@ public class TypeParser {
...
 
-  private static Supplier<TypeManager.Language> languageSupplier =
-      () -> TypeManager.getInstance().getLanguage();
   private static final String VOLATILE_QUALIFIER = "volatile";
```
Comment (maximiliankaul) [inline cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/types/TypeParser.java:56]: Haven't we covered all this stuff with the new language traits?

**Review by maximiliankaul — APPROVED** [review]
Very nice work :+1: Looks good to me.

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/types/TypeParser.java (hunk 34 above)
Comment (KuechA) [reply cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/types/TypeParser.java:56]: We have the keywords but not the interpretation for the mapping to the class `Type.Qualifier`.

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/types/TypeParser.java (hunk 33 above)
Comment (KuechA) [reply cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/types/TypeParser.java:54]: Good question. There's also a regex in the `TypeManager` (`funPointerPattern`) which looks quite different

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/Language.kt [hunk 35]
```diff
@@ -0,0 +1,86 @@
...
+    /** The namespace delimiter used by the language. Often, this is "." */
+    abstract val namespaceDelimiter: String
+
+    @get:JsonSerialize(using = KClassSerializer::class)
+    /** The class of the frontend which is used to parse files of this language. */
+    abstract val frontend: KClass<out T>
+
+    /** The primitive types of this language. */
+    open val primitiveTypes: Set<String>
+        get() = setOf("byte", "short", "int", "long", "float", "double", "boolean", "char")
```
[the remark this answers is not in the document]
Comment (KuechA) [reply cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/Language.kt:59]: To reduce the amount of copy and paste. Each language can still override this set.

File: cpg-core/specifications/language.md [hunk 36]
```diff
@@ -0,0 +1,33 @@
...
+* Are function pointers supported?
+* Are templates or generics used in the language?
+
+These traits are used during the pass execution phase to fine-tune things like call resolution or type hierarchies.
+
+## `LanguageFrontend`
+
+In contrast to the `Language` concept, which represents the generic concept of a programming language, a `LanguageFrontend` is a specific module in the CPG library that does the actual translating of a programming language's source code into our CPG representation.
+
+At minimum a language frontend needs to parse the languages' abstract syntax tree (AST) into specific CPG nodes, seit their `AST` edges and establish proper scopes via the scope manager. Everything else, such as call or symbol resolving is optional and will be done by later passes. However, if a language frontend is confident in setting edges, such as `REFERS_TO`, it is allowed to and this is respected by later passes. However, one must be extremely careful in doing so.
```
[the remark this answers is not in the document]
Comment (oxisto) [reply cpg-core/specifications/language.md:29]: Yes we should re-phrase this

File: cpg-core/specifications/language.md (hunk 32 above)
Comment (oxisto) [reply cpg-core/specifications/language.md:1]: Both good ideas. In the long run I want to add this to the generated doc. In short I’ll add a link in the readme

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontend.kt [hunk 37]
```diff
@@ -151,14 +151,13 @@ class CXXLanguageFrontend(
                 if (topLevel != null) {
```
Comment (KuechA) [inline cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontend.kt:151]: This whole method seems to be very complicated to check if the `path` is contained in the `list`. Why isn't it something like `list.any{Files.isSameFile(it, path)}`?

Comment (oxisto) [reply cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontend.kt:151]: We basically need to check if any of the includeLocations + path is in list. Not sure if this can be achieved any easier.

Comment (oxisto) [reply cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontend.kt:151]: Maybe `includeLocations.any { include -> list.any { Files.isSameFile(it, include.relativize(path)) } }` could work

Comment (oxisto) [reply cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CXXLanguageFrontend.kt:151]: Nope, doesn't since relative can throw an error (which we ignore) if the paths are not relative to each other :(

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageFrontend.kt [hunk 38]
```diff
@@ -0,0 +1,224 @@
...
+    }
+
+    /**
+     * Merges two regions. The new region contains both and is the minimal region to do so.
+     *
+     * @param regionOne the first region
+     * @param regionTwo the second region
+     * @return the merged region
+     */
+    fun mergeRegions(regionOne: Region, regionTwo: Region): Region {
```
[the remark this answers is not in the document]
Comment (oxisto) [reply cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageFrontend.kt:177]: It's probably the best place for now, since the Region class is java and I think we converted enough in this PR.

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/types/TypeParser.java (hunk 33 above)
Comment (oxisto) [reply cpg-core/src/main/java/de/fraunhofer/aisec/cpg/graph/types/TypeParser.java:54]: I have added a TODO to this, let's overhaul this when we overhaul the type system.

File: README.md [hunk 39]
```diff
@@ -11,6 +11,14 @@ A code property graph (CPG) is a representation of source code in form of a labe
 This library uses [Eclipse CDT](https://www.eclipse.org/cdt/) for parsing C/C++ source code [JavaParser](https://javaparser.org/) for parsing Java. In contrast to compiler AST generators, both are "forgiving" parsers that can cope with incomplete or even semantically incorrect source code. That makes it possible to analyze source code even without being able to compile it (due to missing dependencies or minor syntax errors). Furthermore, it uses [LLVM](https://llvm.org) through the [javacpp](https://github.com/bytedeco/javacpp) project to parse LLVM IR. Note that the LLVM IR parser is *not* forgiving, i.e., the LLVM IR code needs to be at least considered valid by LLVM. The necessary native libraries are shipped by the javacpp project for most platforms.
 
 
+## Specifications
```
Comment (konradweiss) [inline README.md:14]: We can check if we can put all specifications into the wiki, if the rendering of the graphs is supported there, but I would do that in a later PR.

File: cpg-console/src/main/kotlin/de/fraunhofer/aisec/cpg/console/Extensions.kt [hunk 40]
```diff
@@ -253,7 +252,7 @@ fun getFanciesFor(original: Node, node: Node): List<Pair<AttributedStyle, Region
             fancyWord("new", node, list, styles.keyword)
 
             // check for primitive types
-            for (primitive in TypeParser.PRIMITIVES) {
+            for (primitive in node.language?.primitiveTypes?.toMutableList() ?: listOf()) {
```
Comment (konradweiss) [inline cpg-console/src/main/kotlin/de/fraunhofer/aisec/cpg/console/Extensions.kt:255]: We can make this non mutable lists, its not important issue, but I would change this alongside, if we are touching this PR to fix other stuff

File: cpg-console/src/main/kotlin/de/fraunhofer/aisec/cpg/console/Extensions.kt [hunk 41]
```diff
@@ -294,7 +293,7 @@ private fun fancyType(
     node: HasType,
     list: MutableList<Pair<AttributedStyle, Region>>
 ) {
-    val types = TypeParser.PRIMITIVES.toMutableSet()
+    val types = outer.language?.primitiveTypes?.toMutableSet() ?: mutableSetOf()
```
Comment (konradweiss) [inline cpg-console/src/main/kotlin/de/fraunhofer/aisec/cpg/console/Extensions.kt:296]: Same here

File: cpg-core/specifications/language.md (hunk 32 above)
Comment (konradweiss) [reply cpg-core/specifications/language.md:1]: I would move this to the wiki itself if the wiki allows rendering of the graphs, and then make links from the main read.me to the wiki, which should already be tere

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CPPLanguage.kt [hunk 42]
```diff
@@ -0,0 +1,315 @@
...
+import de.fraunhofer.aisec.cpg.graph.types.Type
+import de.fraunhofer.aisec.cpg.passes.*
+import de.fraunhofer.aisec.cpg.passes.inference.inferFunction
+import de.fraunhofer.aisec.cpg.passes.inference.startInference
+import de.fraunhofer.aisec.cpg.passes.scopes.ScopeManager
+import java.util.regex.Pattern
+import kotlin.reflect.KClass
+
+/** The C++ language. */
+class CPPLanguage :
```
Comment (konradweiss) [inline cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/cpp/CPPLanguage.kt:45]: Can we make the CPPLanguage make inherit from the CLanguage? I just had this idea but am not sure if thats a good idea. It should simplify the code though. We would of course have to check if we can extend the lists with the additional keywords added in CPP

**Review by konradweiss — APPROVED** [review]

File: cpg-console/src/main/kotlin/de/fraunhofer/aisec/cpg/console/Extensions.kt (hunk 41 above)
Comment (KuechA) [reply cpg-console/src/main/kotlin/de/fraunhofer/aisec/cpg/console/Extensions.kt:296]: We add a value to the set in the next line, so it has to be mutable

File: cpg-core/specifications/language.md (hunk 32 above)
Comment (oxisto) [reply cpg-core/specifications/language.md:1]: This discussion is probably outside of the scope of the PR but I would actually prefer a good generated documentation on some github.io page instead of the wiki that also includes these specifications, but let's discuss this separately.

File: cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageTraits.kt (hunk 21 above)
Comment (oxisto) [reply cpg-core/src/main/java/de/fraunhofer/aisec/cpg/frontends/LanguageTraits.kt:136]: We keep it like this until the type system revamp

**Review by oxisto — APPROVED** [review]
